<template>
  <v-container class="grey lighten-5">
    <v-row class="mb-6" no-gutters>
      <v-col>         
        <h3>GENERAL</h3>
        <v-divider></v-divider>
        <v-row>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-text-field
              v-model="infoGeneralProyecto.nombre"
              :rules="proyectoRules"
              label="Nombre"
              outlined
              dense
            ></v-text-field>
          </v-col>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-text-field
              v-model="infoGeneralProyecto.codigo"
              :rules="proyectoRules"
              label="Código"
              outlined
              dense
            ></v-text-field>
          </v-col>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-select
              v-model="infoGeneralProyecto.celulas"
              :rules="celulasRules" 
              :items="listaCelulas"
              label="Celulas"
              multiple
              persistent-hint
              outlined
              dense
              item-text="nombre"
              item-value="id"
            ></v-select>
          </v-col>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-text-field
              v-model="infoGeneralProyecto.valorC"
              :rules="proyectoRules"
              label="Valor Contrato"
              outlined
              dense
              type="number"
            ></v-text-field>
          </v-col>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-text-field
              v-model="infoGeneralProyecto.presupuestoObra"
              :rules="proyectoRules"
              label="Presupuesto de Obra"
              outlined
              dense
            ></v-text-field>
          </v-col>
          <v-col
            cols="2"
            class="pb-0"
          >
            <v-select
              v-model="infoGeneralProyecto.estado"
              :items="listaEstados"
              label="Estado"
              outlined
              dense
              item-text="nombre"
              item-value="id"
              value="1"
            ></v-select>
          </v-col>
             
        </v-row>
        <v-row>
          <v-col
            cols="2"
            class="pt-0"
          >
            <v-select
              v-model="infoGeneralProyecto.monedaGeneral"
              :rules="proyectoRules"
              :items="listaMonedas"
              label="Moneda"
              dense
              outlined
              item-text="nombre"
              item-value="id"
            ></v-select>
          </v-col>
          <v-col
            class="pt-0"
            cols="2"
          >
            <v-select
              v-model="infoGeneralProyecto.flag"
              :items="listaFlags"
              label="Etiquetas"
              multiple
              persistent-hint
              outlined
              dense
              item-text="nombre"
              item-value="id"
            ></v-select>
         
          </v-col>
          <!-- <v-col
            class="pt-0"
            cols="2"
          >
            <v-select
              v-model="infoGeneralProyecto.monedaPersonalizada"
              :items="monedero"
              label="Monedas Permitidas"
              multiple
              persistent-hint
              outlined
              dense
              item-text="mon.nombre"
            ></v-select>
          </v-col> -->
          <v-col
            class="pt-0"
            cols="2"
          >
            <v-text-field
              v-model="infoGeneralProyecto.ocInicial"
              label="OC inicial"
              outlined
              dense
              value="0"
            ></v-text-field>
          </v-col>
          <v-col
            class="pt-0"
            cols="4"
          >
            <v-textarea
              v-model="infoGeneralProyecto.descripcion"
              label="Descripción"
              auto-grow
              outlined
              rows="1"
              row-height="15"
              dense
            ></v-textarea>
          </v-col>
          <v-col
            cols="4"
          >
            <v-combobox
              v-model="usuarioAdministrador"
              :rules="proyectoRules"
              :items="listaUsuarios"
              label="Administrador de Obra"
              dense
              outlined
              solo
              :item-text="unirNombreApellido"
            ></v-combobox>
          </v-col>
          <v-col
            cols=""
          >
            <v-file-input
              v-model="usuario.firma" 
              label="Imagen"
              outlined
              dense
              :prepend-icon="false"
              append-icon="mdi-camera"
              @change="previewFirma"
              @click:clear="eliminarFirma"
            ></v-file-input>
          </v-col>
          <v-col
            cols="2"
          >
            <v-img :src="url2" max-height="1000" max-width="2000" contain></v-img>
          </v-col>
        </v-row></v-col></v-row>
    <h3>DIRECCIÓN</h3>
    <v-divider></v-divider>
    <v-row>
      <v-col
        cols="2"
      >
        <v-select
          v-model="infoDireccionProyecto.region"
          :items="listaRegion"
          label="Region"
          outlined
          dense
          item-text="nombre"
          item-value="id"
          @blur="cargarComunas()"
        ></v-select>
      </v-col>
      <v-col
        cols="2"
      > 
        <v-select
          v-model="infoDireccionProyecto.comuna"
          :items="listaComunas && listaComunas"
          label="Comuna"
          outlined
          dense
          item-text="nombre"
          item-value="id"
        ></v-select>
      </v-col>
      <v-col
        cols="2"
      >
        <v-text-field
          v-model="infoDireccionProyecto.direccion"
          label="Dirección"
          outlined
          dense
        ></v-text-field>
      </v-col>
             
    </v-row>
    <h3>MANDANTE</h3>
    <v-divider></v-divider>
    <v-row>
      <v-col
        cols="4"
      >
        {{ listaMandante }}
        <v-autocomplete
          v-model="infoMandanteProyecto.mandante"
          :items="listaMandante"
          :loading="isLoading"
          :search-input.sync="search"
          item-text="razon_social"
          item-value="id"
          label="Proveedor"
          hide-no-data
          hint="Puedes buscar por nombre o por rut"
          return-object
          outlined
          dense
        ></v-autocomplete>
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
      >
        <v-btn
          color="success"
          dark
          large
          @click="guardarInformacion()"
        ><v-icon>mdi-content-save-all</v-icon> 
          GUARDAR
        </v-btn> 
         
      </v-col></v-row>

  </v-container>
</template>
<script src="./InformacionGeneral.js"></script>
